sudo: false

language: python

python:
  - "3.6"

install:
  - sudo apt-get install hugo

script:
  - hugo -t even

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  keep-history: true
  repo: xlk3099/xlk3099.github.io
  target_branch: master