sudo: false

language: go

go:
  - "1.11"
  
env:
  - GO111MODULE=on
  
git:
  depth: 1

install: 
  - cd ${TRAVIS_HOME}/gopath/src/
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - go get ./...
  - go install
  - cd ${TRAVIS_HOME}/gopath/src/github.com/xlk3099/blogs

script:
  - hugo -t even

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: xlk3099/xlk3099.github.io
  target_branch: master
  email: xlk3099@gmail.com
  name: xlk3099